# Generated by Django 6.1 on 2026-08-26 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_favorite_options_alter_shoppingcart_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Время приготовления должно быть >= 1 минуты"
                    )
                ],
                verbose_name="Время приготовления в минутах",
            ),
        ),
    ]
