# Generated by Django 6.1 on 2026-09-15 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_recipe_cooking_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "ordering": ["id"],
                "verbose_name": "избранное",
                "verbose_name_plural": "Избранное",
            },
        ),
        migrations.AlterModelOptions(
            name="recipeingredient",
            options={
                "ordering": ["recipe", "ingredient"],
                "verbose_name": "ингредиент в рецепте",
                "verbose_name_plural": "Ингредиенты в рецептах",
            },
        ),
        migrations.AlterModelOptions(
            name="recipetag",
            options={
                "ordering": ["recipe", "tag"],
                "verbose_name": "тег рецепта",
                "verbose_name_plural": "Теги рецептов",
            },
        ),
        migrations.AlterModelOptions(
            name="shoppingcart",
            options={
                "ordering": ["id"],
                "verbose_name": "список покупок",
                "verbose_name_plural": "Списки покупок",
            },
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Время приготовления не может быть меньше 1 минуты."
                    ),
                    django.core.validators.MaxValueValidator(
                        32000,
                        message="Время приготовления не может быть больше 32000 минут.",
                    ),
                ],
                verbose_name="Время приготовления в минутах",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Количество не может быть меньше 1."
                    ),
                    django.core.validators.MaxValueValidator(
                        32000, message="Количество не может быть больше 32000."
                    ),
                ],
                verbose_name="Количество",
            ),
        ),
    ]
