# Generated by Django 6.1 on 2026-08-21 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="follow",
            options={
                "ordering": ("author",),
                "verbose_name": "подписка",
                "verbose_name_plural": "Подписки",
            },
        ),
    ]
