# Generated by Django 6.1 on 2026-09-15 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_follow_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="follow",
            options={
                "ordering": ["author"],
                "verbose_name": "подписка",
                "verbose_name_plural": "Подписки",
            },
        ),
    ]
